server:
  # 端口号
  port: 7777
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    # password: 123456 # Redis服务器连接密码（默认为空）
    database: 0 # Redis数据库索引（默认为0）
    timeout: 3000ms # 连接超时时间（毫秒）
    client-type: lettuce # 配置客户端技术类型，设置为lettuce
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数，默认8（使用负值表示没有限制）
        max-wait: 100ms # 连接池最大阻塞等待时间，默认-1（使用负值表示没有限制）
        max-idle: 8     # 连接池最大空闲连接，默认8
        min-idle: 0     # 连接池中最小空闲连接，默认0
    jedis:
      pool:
        max-active: 8   # 连接池最大连接数，默认8（使用负值表示没有限制）
        max-wait: 100ms # 连接池最大阻塞等待时间，默认-1（使用负值表示没有限制）
        max-idle: 8     # 连接池最大空闲连接，默认8
        min-idle: 0     # 连接池中最小空闲连接，默认0
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

# MyBatis-Plus相关配置
mybatis-plus:
  configuration:
    # 配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 全局配置
  global-config:
    db-config:
      # 设置所有表的通用前缀名称为t_
      table-prefix: t_
      # 设置主键的生成策略（assign_id雪花算法，auto自增）
      id-type: auto
      logic-delete-field: delFlag # 全局逻辑删除的实体字段名
      logic-delete-value: 1  # 代表已删除
      logic-not-delete-value: 0 # 代表未删除

oss:
  accessKey: N7K_UjpRZc5LhbkH1dlha26c-ZxjhRWeOSjPKMe1 # 密钥AK
  secretKey: Pwn2KFbOIKusnf7KY9LMMnK5t5Ry0U0uDwfviJrv # 密钥SK
  bucket: wen-blog # 空间名称
  testUrl: rhvxagakw.hb-bkt.clouddn.com/ # 七牛云提供的测试域名